#!/usr/bin/env node

const request = require('request-promise');
require('dotenv').config();

const fs = require('fs');


async function main(configurationId, mimeType, path) {
    const clientid = process.env.XILLIO_CLIENTID;
    const clientsecret = process.env.XILLIO_CLIENTSECRET
    const username = process.env.XILLIO_USERNAME;
    const password = process.env.XILLIO_PASSWORD;
    const tenant = process.env.XILLIO_TENANT;

    async function getToken() {
        const authentication = await request({
            method: 'POST',
            uri: `${tenant}/oauth/token`,
            headers: {
                'Authorization': 'Basic ' + Buffer.from(clientid + ':' + clientsecret).toString('base64'),
                'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
            },
            json: true,
            body: 'grant_type=password&username=' + username + '&password=' + password
        })
        return authentication["access_token"];
    }

    async function getContents(configurationId, mimeType, path ) {
        return await request({
            uri: `${tenant}/v2/contents/${configurationId}/${path}`,
            headers: {
                'Authorization': 'Bearer ' + token,
                'Accept': mimeType ? mimeType : 'application/octet-stream'
            },
            json: true,
        });
    }

    const token = await getToken();

    const contents = await getContents(configurationId, mimeType, path);
    console.log(contents);
}

const configurationId = process.argv[2];
const mimeType = process.argv[3];
const path = process.argv[4];

main(configurationId, mimeType, path);