#!/usr/bin/env node
if (process.argv.length !== 4) {
    console.error('Usage:')
    console.error(' testscript <contentscriptpath> <inputfilepath>')
    console.error('Example:')
    console.error(' testscript scripts/json-2-xml.js input/json-2-xml-test.json')
    process.exit(1);
}
const contentscriptFileName = process.argv[2];
const contentscript = require('./' + contentscriptFileName);

const inputFileName = process.argv[3]
const content = require('fs').readFileSync('./' + inputFileName).toString();

console.log(contentscript({content: content}));
